### PR TITLE
Add Typescript typings

### PR DESCRIPTION
**Pull request by yonilerner**

### CODE REVIEW

**Comment by wdavidw** [comment]
Thank you very much. A new version will be available shortly.

**Comment by wdavidw** [comment]
Hi @yonilerner , would you accept to become a contributor and help to maintain the TS files?

**Comment by yonilerner** [comment]
@wdavidw What would that entail?

**Comment by wdavidw** [comment]
That's up to you, we are only volunteering. I surely never used TS but I could get some help managing/answering the issues as well. And there will be a new website soon with hopefully a little more documentation.

**Comment by yonilerner** [comment]
Sure, I can try to stay on top of the TS stuff. I guess I would just need to know when the API changes so I can make sure it stays updated. I can answer questions related to TS too

**Comment by wdavidw** [comment]
Great, you've been invited to the 5 projects

**Comment by yonilerner** [comment]
:+1: 

Are there recent changes that need to be applied to the typings? Also I think I only ever did stringify and parse, so I'll add typings for generate and transform later

**Comment by wdavidw** [comment]
Not sure but you can look at the changelog

**Pull request merged**
