### PR TITLE
Memory leak fix and freeing memory after stringify (sync) function call #120

### PR DESCRIPTION
**Pull request by drdmitry**

### CODE REVIEW

**Comment by wdavidw** [comment]
I have reproduce the leak, it only comes from `sync`, replacing `return data.join('')` by `return data.splice(0).join('')` fix it but why?

I looked at `data`, it is re-initialized on every new call to `stringify`, it is always the same length `100000`. What is even more strange is that simply calling `JSON.stringify(data)` before `return data.join('')` simply fix the leak as well. Did you find out?

I want to make sure we are fixing the root cause and I need a clear understanding of what cause the leak before apply any fix.

**Comment by drdmitry** [comment]
> I have reproduce the leak, it only comes from sync, replacing return data.join('') by return data.splice(0).join('') fix it but why?

That's true for me as well.

> I looked at data, it is re-initialized on every new call to stringify, it is always the same length 100000. What is even more strange is that simply calling JSON.stringify(data) before return data.join('') simply fix the leak as well. Did you find out the source of the leak?

I did some investigation, it turns out that `JSON.stringify` triggers some memory cleanup, but for my real-world data-sets with 1mln records it still didn't free memory for "resources".

I think I found the reason:
https://github.com/adaltas/node-csv-stringify/blob/9e62af7d29578931471415d8aa1d1619176cb3e8/lib/sync.js#L11-L16

here `push` method of the `Transform` stream gets rewritten (see the solution below), and the main problem is that it has a reference to `data` which is outside of the `Stringifier`. Every time `Stringifier` created - it keeps the reference to `data` outside of it (and thus memory can't be released). If we manually clean up the `data` - it helps, but the reference is still there.

The solution would be (1) to use `data` event of the `Transform` stream:
```javascript
  function onData(chunk){
    if(chunk){
      data.push(chunk.toString())
    }
  }
  let stringifier = new stringify.Stringifier(options)
  stringifier.on('data', onData);
```
and (2) to clean up the reference by removing `data` event listener:
```javascript
  stringifier.end()
  stringifier.off('data', onData);
```
Without doing `data.splice(0)`.
I tested on my several datasets - works well, and the test from #120 now returns much better results (looks like memory usage reduced from ~800mb to ~300mb):
```
// testing on 19 iterations
: records created
Memory usage: rss 135.00, heap 84.48 / 115.02
: after stringify # 1
Memory usage: rss 315.50, heap 260.08 / 292.14
: after stringify # 2
Memory usage: rss 316.25, heap 259.49 / 292.12
: after stringify # 3
Memory usage: rss 408.59, heap 349.90 / 383.11
: after stringify # 4
Memory usage: rss 502.13, heap 440.34 / 473.60
: after stringify # 5
Memory usage: rss 594.82, heap 530.80 / 564.34
: after stringify # 6
Memory usage: rss 319.19, heap 259.36 / 291.23
: after stringify # 7
Memory usage: rss 410.66, heap 349.71 / 382.47
: after stringify # 8
Memory usage: rss 502.42, heap 440.12 / 473.21
: after stringify # 9
Memory usage: rss 594.89, heap 530.57 / 563.70
: after stringify # 10
Memory usage: rss 687.02, heap 621.02 / 654.45
: after stringify # 11
Memory usage: rss 318.11, heap 259.54 / 291.80
: after stringify # 12
Memory usage: rss 409.79, heap 349.92 / 383.05
: after stringify # 13
Memory usage: rss 501.92, heap 440.31 / 473.54
: after stringify # 14
Memory usage: rss 319.70, heap 259.52 / 291.87
: after stringify # 15
Memory usage: rss 410.21, heap 349.88 / 383.11
: after stringify # 16
Memory usage: rss 502.41, heap 440.32 / 473.60
: after stringify # 17
Memory usage: rss 594.15, heap 530.83 / 563.34
: after stringify # 18
Memory usage: rss 320.85, heap 259.69 / 291.87
: after stringify # 19
Memory usage: rss 412.08, heap 349.98 / 383.11
```

I am going to update the pull request.

> I want to make sure we are fixing the root cause and I need a clear understanding of what cause the leak before apply any fix.

Thanks for pointing this out.

**Comment by wdavidw** [comment]
Sounds good, please prepare a pull request.

**Comment by drdmitry** [comment]
@wdavidw, I updated this pull request with the fix.

**Pull request merged**
